# The URL the site will be built for
base_url = "https://eneroo.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true



[extra]
# Put all your custom variables here

[[extra.drop_down]]
title= "Kdo tvoří příběh ENEROOO"
description= [
        "<strong>HARDWARIO</strong>: - Kompletní dodávka hardwaru a řídicího systému", 
        "<strong>Evolwings</strong>: - Cloudové služby a vizualizace dat", 
        "<strong>Voltamyt</strong>: - Referenční montáže a budování montážní sítě",
]

[[extra.drop_down]]
title= "Proč si vybrat ENEROOO?"
description= [
        "<strong>Úspora až 20 % nákladů na energii díky kombinaci solární energie a IoT technologií</strong>", 
        "<strong>Bezdrátové IoT sítě pro chytré řízení energetických zařízení</strong>", 
        "<strong>Reálný čas odečtu spotřeby pro větší kontrolu nad náklady</strong>",
]

[[extra.drop_down]]
title= "Chytré technologie v akci"
description= [
        "<strong>Odepínátelné zásuvky řízené výkonem solárního systému</strong>", 
        "<strong>Termostatické hlavice s dálkovým nastavením</strong>", 
        "<strong>Reálný čas odečtu energíí</strong>",
]